# Generated by Django 4.0.4 on 2022-05-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.ManyToManyField(related_name='product_color', to='stores.colorproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(related_name='product_size', to='stores.sizeproduct'),
        ),
    ]
